Repository PI20v/awesome-email-extractor, pull requests merged in 2022-05, with the labels that each got.

#5 Добавляет главное окно
  MainForm.Designer.cs
  MainForm.resx
Labels: enhancement

#6 Добавляет алгоритм извлечения адресов
  AwesomeEmailExtractor.csproj
  ExtactEmailsAlgorithm.cs
Labels: enhancement

#8 Интегрирует алгоритм в GUI
  MainForm.Designer.cs
  MainForm.cs
  MainForm.resx
Labels: enhancement

#18 Добавляет форму авторизации
  .vs/AwesomeEmailExtractor/project-colors.json
  AuthorizationForm.Designer.cs
  AuthorizationForm.cs
  AuthorizationForm.resx
  AwesomeEmailExtractor.csproj
Labels: enhancement

#17 Добавляет механизм авторизации и регистрации
  Authorization.cs
  AuthorizationForm.Designer.cs
  AuthorizationForm.cs
  AwesomeEmailExtractor.csproj
  FormManager.cs
  Globals.cs
  Logs.cs
  MainForm.cs
  Program.cs
  RegistrationForm.Designer.cs
  RegistrationForm.cs
  packages.config
Labels: enhancement

#25 Обновляет главное окно
  Authorization.cs
  AwesomeEmailExtractor.csproj
  MainForm.Designer.cs
  MainForm.cs
  SettingsForm.Designer.cs
  SettingsForm.cs
  SettingsForm.resx
Labels: enhancement

#31 Добавляет экспорт результата в файл
  MainForm.Designer.cs
  MainForm.cs
Labels: enhancement

#32 Добавляет проверки на ввод
  Authorization.cs
  AuthorizationForm.cs
  EditUserForm.cs
  RegistrationForm.cs
  SettingsForm.cs
Labels: enhancement

#33 Добавляет меню со справкой
  AwesomeEmailExtractor.csproj
  HelpForm.Designer.cs
  HelpForm.cs
  HelpForm.resx
  MainForm.Designer.cs
  MainForm.cs
Labels: documentation, enhancement

#34 Изменил регулярное выражение
  ExtactEmailsAlgorithm.cs
Labels: bug

#35 0.3
  AdministrationForm.Designer.cs
  AdministrationForm.cs
  AdministrationForm.resx
  Authorization.cs
  AuthorizationForm.cs
  AwesomeEmailExtractor.csproj
  EditUserForm.Designer.cs
  EditUserForm.cs
  EditUserForm.resx
  ExtactEmailsAlgorithm.cs
  Globals.cs
  HelpForm.Designer.cs
  HelpForm.cs
  HelpForm.resx
  JournalForm.Designer.cs
  JournalForm.cs
  JournalForm.resx
  Logs.cs
  MainForm.Designer.cs
  MainForm.cs
  RegistrationForm.Designer.cs
  RegistrationForm.cs
  SettingsForm.Designer.cs
  SettingsForm.cs
Labels: enhancement
